export enum UserEvents {
  UPDATE_AVAILABILITY = 'user:update_availability',
  LOGOUT = 'user:logout',
  REQUEST_CONNECTION = 'user:request_connection',
  NEW_REQUEST_CONNECTION = 'user:new_request_connection',
  ACCEPT_REQUEST = 'user:accept_request',
  REQUEST_ACCEPTED = 'user:request_accepted',
  REJECT_CONNECTION = 'user:reject_connection',
  CONNECTION_REJECTED = 'user:connection_rejected',
  CANCEL_CONNECTION = 'user:cancel_connection',
  CONNECTION_CANCELED = 'user:connection_canceled',
  REMOVE_PARTNER = 'user:remove_partner',
  REMOVED_PARTNER = 'user:removed_partner',
  LOGOUT_DEVICE = 'user:logout_device',
  READ_ALL_NOTIFICATIONS = 'user:read_all_notifications',
  READ_NOTIFICATION = 'user:read_notification',
  NOTIFICATIONS_READ = 'user:notifications_read',
}
